# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_pickle', models.CharField(max_length=100000)),
                ('state_timestamp', models.DateTimeField(verbose_name=b'state timestamp')),
                ('mode', models.CharField(max_length=100)),
                ('fan', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('target', models.FloatField()),
                ('away_heat', models.FloatField()),
                ('away_cool', models.FloatField()),
                ('hvac_ac_state', models.BooleanField()),
                ('hvac_cool_x2_state', models.BooleanField()),
                ('hvac_heater_state', models.BooleanField()),
                ('hvac_aux_heater_state', models.BooleanField()),
                ('hvac_heat_x2_state', models.BooleanField()),
                ('hvac_heat_x3_state', models.BooleanField()),
                ('hvac_alt_heat_state', models.BooleanField()),
                ('hvac_alt_heat_x2_state', models.BooleanField()),
                ('hvac_emer_heat_state', models.BooleanField()),
                ('online', models.BooleanField()),
                ('last_ip', models.CharField(max_length=100)),
                ('local_ip', models.CharField(max_length=100)),
                ('last_connection', models.CharField(max_length=100)),
                ('error_code', models.CharField(max_length=100)),
                ('battery_level', models.CharField(max_length=100)),
            ],
        ),
    ]
