# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nest_graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestate',
            name='name',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='devicestate',
            name='weather_pickle',
            field=models.CharField(default=b'', max_length=100000),
        ),
        migrations.AddField(
            model_name='devicestate',
            name='where',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='devicestate',
            name='state_pickle',
            field=models.CharField(default=b'', max_length=100000),
        ),
    ]
