# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nest_graph', '0005_devicestate_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(default=b'NEST', max_length=40),
        ),
    ]
