# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nest_graph', '0006_device_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='nest_graph.UserProfile'),
        ),
        migrations.AlterField(
            model_name='devicestate',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='nest_graph.Device'),
        ),
    ]
