# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nest_graph', '0007_auto_20160206_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nest_password',
            field=models.CharField(default=b'', max_length=40),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nest_username',
            field=models.CharField(default=b'', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
