# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-29 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nest_graph', '0008_auto_20160206_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='NEST', max_length=40),
        ),
        migrations.AlterField(
            model_name='devicestate',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='devicestate',
            name='state_pickle',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='devicestate',
            name='state_timestamp',
            field=models.DateTimeField(verbose_name='state timestamp'),
        ),
        migrations.AlterField(
            model_name='devicestate',
            name='weather_pickle',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='devicestate',
            name='where',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friendly_name',
            field=models.CharField(default='Friend', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nest_password',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nest_username',
            field=models.CharField(default='', max_length=40),
        ),
    ]
