# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-29 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nest_graph', '0009_auto_20171229_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicestate',
            name='away_cool',
        ),
        migrations.RemoveField(
            model_name='devicestate',
            name='away_heat',
        ),
        migrations.RemoveField(
            model_name='devicestate',
            name='hvac_ac_state',
        ),
        migrations.RemoveField(
            model_name='devicestate',
            name='hvac_alt_heat_state',
        ),
        migrations.RemoveField(
            model_name='devicestate',
            name='hvac_alt_heat_x2_state',
        ),
        migrations.RemoveField(
            model_name='devicestate',
            name='hvac_aux_heater_state',
        ),
        migrations.RemoveField(
            model_name='devicestate',
            name='hvac_cool_x2_state',
        ),
        migrations.RemoveField(
            model_name='devicestate',
            name='hvac_emer_heat_state',
        ),
        migrations.RemoveField(
            model_name='devicestate',
            name='hvac_heat_x2_state',
        ),
        migrations.RemoveField(
            model_name='devicestate',
            name='hvac_heat_x3_state',
        ),
        migrations.RemoveField(
            model_name='devicestate',
            name='hvac_heater_state',
        ),
        migrations.RemoveField(
            model_name='devicestate',
            name='last_ip',
        ),
        migrations.RemoveField(
            model_name='devicestate',
            name='local_ip',
        ),
        migrations.RemoveField(
            model_name='devicestate',
            name='state_pickle',
        ),
        migrations.RemoveField(
            model_name='devicestate',
            name='weather_pickle',
        ),
        migrations.AddField(
            model_name='devicestate',
            name='hvac_state',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
